### ISSUE TITLE
Fix semantic versioning

### ISSUE THREAD

**Issue by oferze** [soundaranbu/Razor.Templating.Core#50]
Beginning at version 1.7.0, the package is dependent on .NET Core (specifically.NET 6 I think).
I think this warrants upping to a new major version 2.0.0

Currently, when using the package in a .NET Framework project, NuGet suggests upgrading from say 1.6.0 to 1.7.1 but the upgrade is not possible because of this dependency.

**Comment by soundaranbu** [comment]
What is your .NET version? It won't be possible to use this library in .NET Framework as it targets only .NET Core from the beginning (.NET Core 3.0 & above).

Since v1.7.0, it targets only .NET 6 as it became too difficult to multi target all the lower versions and keep the library working in all new dotnet versions.

`v2.0.0` was not chosen mainly because there's no breaking change in the public API surface.

`net5.0` & below can keep using `v1.6.x` as it's the latest version that they can use and when they upgrade to `net6.0`, simply update the library to the latest version.

The version details are documented in the README file.

Hope this helps. If anything please let me know.

**Comment by soundaranbu** [comment]
Hope I've explained the best that I can. Please feel free to re-open if necessary.
